# Generated by Django 5.2.7 on 2025-10-24 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('running', 'Lari'), ('badminton', 'Badminton'), ('futsal', 'Futsal'), ('football', 'Sepak Bola'), ('basketball', 'Basket'), ('cycling', 'Sepeda'), ('volleyball', 'Voli'), ('yoga', 'Yoga'), ('padel', 'Padel'), ('other', 'Lainnya')], default='other', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_number', models.CharField(blank=True, max_length=12, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_venues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venueModule.venue')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
