# Generated by Django 5.2.7 on 2025-10-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venueModule', '0002_alter_venue_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='category',
            field=models.CharField(choices=[('running', 'Lari'), ('badminton', 'Badminton'), ('futsal', 'Futsal'), ('football', 'Sepak Bola'), ('basketball', 'Basket'), ('cycling', 'Sepeda'), ('volleyball', 'Voli'), ('yoga', 'Yoga'), ('padel', 'Padel'), ('other', 'Lainnya')], default='other', max_length=30),
        ),
    ]
