# Generated by Django 5.2.7 on 2025-10-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venueModule', '0003_venue_contact_number_alter_venue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='contact_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
