# Generated by Django 5.2.5 on 2025-10-23 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='No description available')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='event_thumbnails/')),
                ('category', models.CharField(choices=[('running', 'Lari'), ('badminton', 'Badminton'), ('futsal', 'Futsal'), ('football', 'Sepak Bola'), ('basketball', 'Basket'), ('cycling', 'Sepeda'), ('volleyball', 'Voli'), ('yoga', 'Yoga'), ('padel', 'Padel'), ('other', 'Lainnya')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
