# Generated by Django 5.2.7 on 2025-10-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventMakerModule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('running', 'Lari'), ('badminton', 'Badminton'), ('futsal', 'Futsal'), ('football', 'Sepak Bola'), ('basketball', 'Basket'), ('cycling', 'Sepeda'), ('volleyball', 'Voli'), ('yoga', 'Yoga'), ('padel', 'Padel'), ('other', 'Lainnya')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
