# Generated by Django 5.2.7 on 2025-10-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventMakerModule', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_accepted',
            field=models.BooleanField(default=None),
        ),
    ]
