# Generated by Django 5.2.7 on 2025-10-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventMakerModule', '0003_alter_event_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
