# Generated by Django 5.2.7 on 2025-10-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventModule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventfilter',
            old_name='preferred_catagory',
            new_name='preferred_category',
        ),
    ]
