# Generated by Django 5.2.7 on 2025-10-22 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventModule', '0002_rename_preferred_catagory_eventfilter_preferred_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventFilter',
        ),
    ]
