# Generated by Django 5.2.6 on 2025-12-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventModule', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='category',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='UserEventPreference',
        ),
    ]
