# Generated by Django 5.2.5 on 2025-10-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('running', 'Running'), ('workout', 'Workout'), ('nutrition', 'Nutrition'), ('event', 'Event'), ('recovery', 'Recovery'), ('motivation', 'Motivation')], default='update', max_length=20),
        ),
    ]
