# Generated by Django 5.2.5 on 2025-10-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumModule', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
