# Generated by Django 5.2.5 on 2025-10-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumModule', '0003_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('update', 'Update'), ('exclusive', 'Exclusive'), ('match', 'Match'), ('rumor', 'Rumor'), ('analysis', 'Analysis')], default='update', max_length=20),
        ),
    ]
